this.globalLayout = (function() {
  function globalLayout() {}

  globalLayout.showDialog = function(opts) {
    console.log(opts);
    this.dialog = $("[global-dialog]");
    Session.set("global.ui.dialogData", opts.data);
    Session.set("global.ui.dialogJSONData", opts.jsonOnly);
    Session.set("global.ui.dialogTemplate", opts.template);
    return Tracker.afterFlush((function(_this) {
      return function() {
        return _this.dialog.show();
      };
    })(this));
  };

  globalLayout.closeDialog = function() {
    Session.set("global.ui.dialogTemplate", null);
    return this.dialog.hide();
  };

  return globalLayout;

})();

Template.global.created = function() {
  return Session.set('list', [
    {
      id: Random.id(),
      name: 'Listitem 1'
    }, {
      id: Random.id(),
      name: 'Listitem 2'
    }, {
      id: Random.id(),
      name: 'Listitem 3'
    }
  ]);
};

Template.global.events({
  "click [data-open-dialog]": function(e) {
    var node;
    node = $(e.currentTarget);
    return globalLayout.showDialog({
      data: node.data("useContext"),
      template: node.data("open-dialog"),
      jsonOnly: node[0].getAttribute('data-use-context')
    });
  }
});

Template.global.helpers({
  listItems: function() {
    return Session.get('list');
  }
});

Template.registerHelper('globalDialogTemplate', function() {
  return Session.get("global.ui.dialogTemplate");
});

Template.registerHelper('globalDialogData', function() {
  return Session.get("global.ui.dialogData");
});

// ---
// generated by coffee-script 1.9.2